// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqYQWzoisdyvCRJ3lQH9bMkJbf-fmpI_Q',
    appId: '1:992266342121:android:0bc169cb938a5b1d492a78',
    messagingSenderId: '992266342121',
    projectId: 'flutter-firebase-task-eb768',
    storageBucket: 'flutter-firebase-task-eb768.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNsWLMzs7w1y2r2VkDxbAXppJ5tW-NM7I',
    appId: '1:992266342121:ios:647d83fe7fdb4ffa492a78',
    messagingSenderId: '992266342121',
    projectId: 'flutter-firebase-task-eb768',
    storageBucket: 'flutter-firebase-task-eb768.appspot.com',
    androidClientId: '992266342121-dcgmines93hgs69lcqh9ab35vt4cldq7.apps.googleusercontent.com',
    iosClientId: '992266342121-cenfru7glqq20fc1s56rsf0sh3tuaknp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseTest',
  );
}
